### ISSUE TITLE
vmem=4gb too small?

### ISSUE THREAD

**Issue by soichih** [brain-life/app-splitshells#12]
I am seeing following error message when this App runs on Karst - with HCP 3T subject 108323.

```
** failed to alloc -80548096 bytes for image data
Index exceeds matrix dimensions.

Error in main (line 35)

MATLAB:badsubscript
```

I believe vmem=4gb that's currently configured is too small. 

```
#PBS -l nodes=1:ppn=1,vmem=4gb,walltime=0:20:00
```

I've tried increasing it to 8gb, but it wasn't enough.

```
Error using readFileNifti
Out of memory. Type HELP MEMORY for your options.
```

So, I've tried increased it again to vmem=16gb, and this time it worked.

I am not sure why this App needs so much memory just to split shell, but please update it to use vmem=16gb (and make a new version - maybe 1.1?)

**Comment by soichih** [comment]
I went ahead and increased vmem and create a new branch (1.1)

**Comment by giulia-berto** [comment]
I am seeing this error again (in branch 1.2):
```Error using readFileNifti
Out of memory. Type HELP MEMORY for your options.
```
Can you please increase the memory?
