### ISSUE TITLE
Add check box to round("normalize") bvecs

### ISSUE THREAD

**Issue by soichih** [brain-life/app-splitshells#13]
I think we could deprecate "Round b-values" App by adding "round b-value" option to this App. Doing so will greatly reduce the amount of unnecessary duplication of the dwi datasets currently archived on various project (and make it easier for other users)

Dipy folks has indicated that we shouldn't be rounding bvecs, btw... which I tend to agree. If App needs bvecs to be rounded, it should do so on-the-fly for each App.

**Comment by francopestilli** [comment]
Sounds like a good proposal.

**Comment by soichih** [comment]
Our archive storage space is becoming more of an issue now. I went ahead and merged the app- datanormalize functionality into this app. I will do some testing on test.brainlife.io and update the existing app-splitshell once I confirm that everything still works.
