### ISSUE TITLE
.bvecs .bvals should be delimited by space

### ISSUE THREAD

**Issue by soichih** [brain-life/app-splitshells#8]
Related to this
> https://github.com/brain-life/pestillilab_projects/issues/24

.bvecs / .bvals should be space delimited.

```
dlmwrite('dwi.bvals',bvals.valnorm,'delimiter',' ');
```

**Comment by soichih** [comment]
@kitchell I just noticed that split shell is still outputting comma delimited bvecs/bvals. Can you update this?

**Comment by kitchell** [comment]
I must have missed the original notification. it should be updated now. testing on brainlife.
